services:
  - type: web
    name: prescriptionpro
    env: static
    buildCommand: npm run render-build
    staticPublishPath: dist/prescriptionpro
    publishPath: dist/prescriptionpro
    envVars:
      - key: NODE_VERSION
        value: 20
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000